// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTHVC7tEDLNab8dUYthiuSqccNQ5YgjI',
    appId: '1:1023074990514:web:2dfc9517c8f57f93924cab',
    messagingSenderId: '1023074990514',
    projectId: 'bitleo-48fad',
    authDomain: 'bitleo-48fad.firebaseapp.com',
    storageBucket: 'bitleo-48fad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJqpHb_jYtLLn6glwGim_nuf07helNRs',
    appId: '1:1023074990514:android:d3f7466629e7fae0924cab',
    messagingSenderId: '1023074990514',
    projectId: 'bitleo-48fad',
    storageBucket: 'bitleo-48fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtEtW4MQsPcVLboKjhJe_hpkCHmM8WJ8',
    appId: '1:1023074990514:ios:3e2ec57ffb2b5222924cab',
    messagingSenderId: '1023074990514',
    projectId: 'bitleo-48fad',
    storageBucket: 'bitleo-48fad.firebasestorage.app',
    iosBundleId: 'com.example.bitleo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtEtW4MQsPcVLboKjhJe_hpkCHmM8WJ8',
    appId: '1:1023074990514:ios:3e2ec57ffb2b5222924cab',
    messagingSenderId: '1023074990514',
    projectId: 'bitleo-48fad',
    storageBucket: 'bitleo-48fad.firebasestorage.app',
    iosBundleId: 'com.example.bitleo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfTHVC7tEDLNab8dUYthiuSqccNQ5YgjI',
    appId: '1:1023074990514:web:5170cf968f80bb28924cab',
    messagingSenderId: '1023074990514',
    projectId: 'bitleo-48fad',
    authDomain: 'bitleo-48fad.firebaseapp.com',
    storageBucket: 'bitleo-48fad.firebasestorage.app',
  );
}
